#!/bin/bash
# ---------------------------------------------------------------------------
# makeuser - tilde.club new user creation
# Usage: makeuser [-h|--help] <username> <email> "<pubkey>"
# ---------------------------------------------------------------------------

PROGNAME=${0##*/}
VERSION="0.1"

error_exit() {
  echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
  exit 1
}

usage() {
  echo -e "usage: $PROGNAME [-h|--help] <username> <email> \"<pubkey>\""
}

sub_to_list() {
  echo "
From: $1
Subject: subscribe
" | sudo -u $1 sendmail tildeclub-join@lists.tildeverse.org
}

case $1 in
  -h | --help)
    usage; exit ;;
  -* | --*)
    usage; error_exit "unknown option $1" ;;
  *)
    [[ $# -ne 3 ]] && error_exit "not enough args"

    if id $1 > /dev/null 2>&1; then
	error_exit "user $1 already added"
    fi

    echo "adding new user $1"
    newpw=$(pwgen -1B 10)
    pwcrypt=$(perl -e "print crypt('${newpw}', 'sa');")
    sudo useradd -m -g 100 -p "$pwcrypt" -s /bin/bash $1 \
        || error_exit "couldn't add user"

    echo "sending welcome mail"
    sed -e "s/newusername/$1/g" -e "s/newpassword/$newpw/" /usr/local/bin/welcome-email.tmpl \
        | sendmail $1 $2 root

    echo "subscribing to mailing list"
    sub_to_list $1

    echo "removing .git from new homedir"
    rm -rf /home/$1/.git

    echo "adding ssh pubkey"
    echo "$3" | sudo tee /home/$1/.ssh/authorized_keys

esac

